version: '3.7'

services:
  postgres:
    image: jonixis/postgres-madlib:latest
    container_name: postgres-madlib
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: docker

volumes:
  data:

### DB-Login ###
# pgcli -h localhost -U postgres -d postgres
